### ISSUE TITLE
Origin of EM4325 Code

### ISSUE THREAD

**Issue by tiusty** [shaks13/KopiLuwak#1]
Hi,

I came across your repo that contains code for the EM4325.

I am interested if you wrote the code or if the code had an original origin that is accessible?
I am looking to develop an application with the EM4325 and while I am familiar with it, if there is a pubic SDK or library that interfaces with the EM4325, I would be curious if there is an updated version of the library. This code seems to be about 4 years old. This would be very helpful.

Thanks for your time!

**Comment by shaks13** [comment]
Hello,
this project was the outcome of my work in a previous firm which is closed
now. So that's why there haven't been any more updates since 4 years. We
didn't have the time to finalize a library.
best regards

**Comment by tiusty** [comment]
Great, thanks for the update.
