### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by tiusty** [shaks13/KopiLuwak#2]
Hi,

If you would humor me to answer one question about the EM4325 if you happen to know the answer. If you don't know or don't want to answer no worries.

We are trying to use the Register File to communicate between a RFID Reader and an external device that is connected to the EM4325.

The EM4325 is setup as a SPI slave and the external device is the SPI master.

We are trying to have the EM4325 fire an interrupt when the RFID Reader writes to the Register File (i.e use the comm buffer semaphore).

The way I understand it works is:
Assuming the EM4325 is configured to do signaling via the Comm Buffer Semaphore (I/O Control Word 0x2660)
1. The EM4325 waits for a command from the RFID Reader
2. The RFID Reader writes to the Register File
3. Then when the RFID Reader finishes writing, the EM4325 will fire an interrupt on MISO indicating that there is data available 
4. The external device can then initial SPI communications to read the data from the Register File

Does this workflow sound correct? Right now I am writing to Register File 1 from a RFID Reader and nothing is happening on the MISO pin. Is there a specific command you need to write to the Register File for it to trigger or something? Just want to make sure my idea of what is supposed to happen is correct. I looked into the code you have and it seems like the functionality is available but I have been unable to make it work so far.

**Comment by shaks13** [comment]
Hello,

I'm sorry but I no longer have the hardware to test and give you a hand. I
remember the firmware was working but that was 5 years ago.

best regards

thomas

**Comment by tiusty** [comment]
No worries, thanks for the update.
